RiskApplication/RiskApplication.Web/Models/CustomerVewModel.cs
namespace RiskApplication.Web.Models
{
    public class CustomerVewModel
    {
        public int Id { get; set; }
        public double AverageStake { get; set; }
        public int TotalBets { get; set; }
        public int TotalBetsWon { get; set; }
        public double WinningPercentage { get; set; }
    }
}

RiskApplication/RiskApplication.Web/Models/Mapper/CustomerProfile.cs
using AutoMapper;
using RiskApplication.Domain.Models;

namespace RiskApplication.Web.Models.Mapper
{
    public class CustomerProfile : Profile
    {
        protected override void Configure()
        {
            CreateMap<Customer, CustomerVewModel>();
        }
    }
}

RiskApplication/RiskApplication.Web/Models/Mapper/RiskProfile.cs
using AutoMapper;
using RiskApplication.Domain.Models;

namespace RiskApplication.Web.Models.Mapper
{
    public class RiskProfile : Profile
    {
        protected override void Configure()
        {
            CreateMap<UnsettledBetRiskAnalysis, UnsettledBetAndRiskViewModel>()
                .ForMember(p => p.CustomerId, opt => opt.MapFrom(t => t.UnsettledBet.CustomerId))
                .ForMember(p => p.Event, opt => opt.MapFrom(t => t.UnsettledBet.Event))
                .ForMember(p => p.Participant, opt => opt.MapFrom(t => t.UnsettledBet.Participant))
                .ForMember(p => p.Stake, opt => opt.MapFrom(t => t.UnsettledBet.Stake))
                .ForMember(p => p.ToWin, opt => opt.MapFrom(t => t.UnsettledBet.ToWin))
                .ForMember(p => p.IsHighPrice, opt => opt.MapFrom(t => t.RiskAnalysis.IsHighPrice))
                .ForMember(p => p.IsHighStake, opt => opt.MapFrom(t => t.RiskAnalysis.IsHighStake))
                .ForMember(p => p.IsUnusuallyHighStake, opt => opt.MapFrom(t => t.RiskAnalysis.IsUnusuallyHighStake))
                .ForMember(p => p.HasUnusualWinRate, opt => opt.MapFrom(t => t.RiskAnalysis.HasUnusualWinRate));
        }
    }
}

RiskApplication/RiskApplication.Web/Models/Mapper/SettledBetProfile.cs
using AutoMapper;
using RiskApplication.Domain.Models;

namespace RiskApplication.Web.Models.Mapper
{
    public class SettledBetProfile : Profile
    {
        protected override void Configure()
        {
            CreateMap<SettledBet, SettledBetVewModel>();
        }
    }
}

RiskApplication/RiskApplication.Web/Models/SettledBetVewModel.cs
namespace RiskApplication.Web.Models
{
    public class SettledBetVewModel
    {
        public int CustomerId { get; set; }
        public int Event { get; set; }
        public int Participant { get; set; }
        public int Stake { get; set; }
        public int Win { get; set; }
    }
}

RiskApplication/RiskApplication.Web/Models/UnsettledBetAndRiskViewModel.cs
namespace RiskApplication.Web.Models
{
    public class UnsettledBetAndRiskViewModel
    {
        public int CustomerId { get; set; }
        public int Event { get; set; }
        public int Participant { get; set; }
        public int Stake { get; set; }
        public int ToWin { get; set; }
        public double WinningPercentage { get; set; }
        public bool IsHighPrice { get; set; }
        public bool IsUnusuallyHighStake { get; set; }
        public bool IsHighStake { get; set; }
        public bool HasUnusualWinRate { get; set; }
    }
}

RiskApplication/RiskApplication.Web/Controllers/RiskController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using RiskApplication.Domain;
using RiskApplication.Web.Models;

namespace RiskApplication.Web.Controllers
{
    public class RiskController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IRiskAnalysisService _riskAnalysisService;

        public RiskController(IRiskAnalysisService riskAnalysisService, IMapper mapper)
        {
            _mapper = mapper;
            _riskAnalysisService = riskAnalysisService;
        }

        public ActionResult Index()
        {
            var betsAndRisks = _riskAnalysisService.GetUnsettledBetsRiskAnalysis();
            var list = _mapper.Map<IEnumerable<UnsettledBetAndRiskViewModel>>(betsAndRisks.ToList());
            return View(list);
        }

        public ActionResult CustomerSettledBets()
        {
            var customers = _riskAnalysisService.GetCustomers();
            var list = _mapper.Map<IEnumerable<CustomerVewModel>>(customers);
            return View(list);
        }

        [Route("/Risk/GetSettledBet/{id}")]
        public ActionResult GetSettledBet(int id)
        {
            var settledBets = _riskAnalysisService.ReadAllSettledBets(id);
            var list = _mapper.Map<IEnumerable<SettledBetVewModel>>(settledBets);
            return PartialView("SettledBets", list);
        }
    }
}

RiskApplication/RiskApplication.Web/Views/Risk/CustomerSettledBets.cshtml
@model IEnumerable<RiskApplication.Web.Models.CustomerVewModel>

<h2>Customers Statistics</h2>
<table class="table table-bordered table-hover" id="statistics">
    <thead class="thead-inverse">
    <tr>
        <th>Customer</th>
        <th>Average stake</th>
        <th>Total wins</th>
        <th>Total bets</th>
        <th>Winning percentage</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr class='@(item.WinningPercentage > 60 ? "danger" : "info")'>
            <td class="col-md-2">@item.Id</td>
            <td class="col-md-2">@item.AverageStake.ToString("N")$</td>
            <td class="col-md-2">@item.TotalBetsWon</td>
            <td class="col-md-2">@item.TotalBets</td>
            <td class="col-md-4">@item.WinningPercentage.ToString("N")%</td>
        </tr>
    }
    </tbody>
</table>

<div id="settledBets">

</div>

@section scripts
{
    <script src="~/Scripts/MasterDetail.js"> </script>
}

RiskApplication/RiskApplication.Web/Views/Risk/Index.cshtml
@model IEnumerable<RiskApplication.Web.Models.UnsettledBetAndRiskViewModel>

<h2>Unsettled bets & their risks</h2>

<table class="table table-hover" id="statistics">
    <thead class="thead-inverse">
    <tr>
        <th>Customer</th>
        <th>Event</th>
        <th>Participant</th>
        <th>Stake</th>
        <th>To win</th>
        <th>High prize</th>
        <th>High stake</th>
        <th>Unusually high stake</th>
        <th>Unusually high win rate</th>
        <th>Win rate</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        var risk = @item.IsHighPrice || @item.IsHighStake || @item.IsUnusuallyHighStake || @item.HasUnusualWinRate;

        <tr class='@(risk ? "danger" : "info")'>
            <td class="col-md-1">@item.CustomerId</td>
            <td class="col-md-1">@item.Event</td>
            <td class="col-md-1">@item.Participant</td>
            <td class="col-md-1">@item.Stake.ToString("N")</td>
            <td class="col-md-1">@item.ToWin.ToString("N")$</td>
            <td class="col-md-1">@item.IsHighPrice</td>
            <td class="col-md-1">@item.IsHighStake</td>
            <td class="col-md-2">@item.IsUnusuallyHighStake</td>
            <td class="col-md-2">@item.HasUnusualWinRate</td>
            <td class="col-md-1">@item.WinningPercentage.ToString("N")%</td>
        </tr>
    }
    </tbody>
</table>

RiskApplication/RiskApplication.Web/Views/Risk/SettledBets.cshtml
@using System.Diagnostics
@model IEnumerable<RiskApplication.Web.Models.SettledBetVewModel>

@{
    var customer = @Model != null && @Model.Any() ? @Model.First().CustomerId.ToString() : string.Empty;
}

<h2>customer's Settled bets : @customer</h2>
<table class="table table-bordered table-hover" id="statistics">
    <thead class="thead-inverse">
    <tr>
        <th>Customer</th>
        <th>Participant</th>
        <th>Event</th>
        <th>Stake</th>
        <th>Won</th>
    </tr>
    </thead>
    <tbody>

    @{
        Debug.Assert(Model != null, "Model != null");
    }

    @foreach (var item in Model)
    {
        <tr>
            <td class="col-md-2">@item.CustomerId</td>
            <td class="col-md-2">@item.Participant</td>
            <td class="col-md-2">@item.Event</td>
            <td class="col-md-2">@item.Stake.ToString("N")$</td>
            <td class="col-md-4">@item.Win.ToString("N")$</td>
        </tr>
    }
    </tbody>
</table>

RiskApplication/RiskApplication.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Risk Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Risk Analysis", "Index", "Risk", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Customer Settled Bets", "CustomerSettledBets", "Risk")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()        
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>